views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from ClassesAndMethods import getTableContent,threads,getPostsOfThread

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    threadList=getTableContent(threads)
    for t in threadList:
        print(t)
    return render_template("home.html",user=current_user,prova="ciao",tList=threadList)

@views.route('/thread/<id>')
@login_required
def see_thread(id):
    return render_template("threads.html",user=current_user,posts=getPostsOfThread(id))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <title>{% block title %} Base {% endblock %}</title>
    <link rel="stylesheet" href="../static/css/style.css">

  </head>
<body>

  
<section class="bg-dark warning p-5 p-lg-0 pt-lg-5 text-center text-sm-start" style="z-index:10" >
<h1 class="text-warning d-flex justify-content-center">IL FORUM ITALICO</h1>
</section>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index: 10">

  <div class="container-fluid" style="z-index: 10">
    <a class="navbar-brand" href="#">IL FORUM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="z-index: 10">
      <div class="navbar-nav">
        {%  if user.is_authenticated %}
        <a class="nav-link" aria-current="page" id="home "href="/">Pagina Casa</a>
        <a class="nav-link" id="logOut" href="/logout">Logout</a>
        <a class="nav-link" href="profilo">Il mio profilo</a>
        {% else %}
        <a class="nav-link" id="login" href="/login">Login</a>
        <a class="nav-link" id="signUp" href="/sign-up">Signup</a>
        {% endif %}
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Inserisci un testo" aria-label="Search">
        <button class="btn btn-outline-warning" type="submit">Ricerca</button>
      </form>
      </div>
    </div>
  </div>
</nav>
{% with messages = get_flashed_messages(with_categories = true) %}
{%  if messages %}
  {%  for category, message in messages %}
  {%  if category == 'error' %}
    <div class="alert alert-danger fade show" role="alert">
      {{  message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{  message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true"> X </span>
      </button>
    </div>
  {%  endif %}
  {%  endfor %}
{%  endif %}
{%  endwith %}


<div class="container">
    {% block content %} {% endblock %}
</div>

<script
type="text/javascript"
src="{{ url_for('static',filename='index.js') }}"
>
</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Changed{% endblock %}

{% block content %} 
<h1>Benvenuto</h1>
{{prova}}
<ul>
    {% for t in tList %}
    <li>{{t.name}} se ti interessa clicca <a href="{{ url_for('views.see_thread', id= 1 )}}">Qua</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Titolo</title>
</head>
<body>

<div class="py-2 w-75 mx-5 border border-3 border-primary px-2 py-1 rounded" style="background-color: #eee;">
ciao
</div>

</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

<div class="sidenav">
   <div class="login-main-text">
      <h2>Forum<br> Login Page</h2>
      <p>Registrati o accedi.</p>
   </div>
</div>
<div class="main">
   <div class="col-md-6 col-sm-12">
      <div class="login-form">
         <form method="POST">
            <h3 align="center">Login</h3>
            <div class="form-group">
              <label for="username">Username</label>
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
                placeholder="Enter Username"
              />
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Enter password"
              />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
      <p>Non hai un account? <a href="sign-up">Clicca qui</a></p>
      </div>
   </div>
</div>

{% endblock %}




<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


<div class="sidenav">
         <div class="login-main-text">
            <h2>Forum<br> Login Page</h2>
            <p>Registrati o accedi.</p>
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form>
                  <div class="form-group">
                     <label>User Name</label>
                     <input type="text" class="form-control" placeholder="User Name">
                  </div>
                  <div class="form-group">
                     <label>Password</label>
                     <input type="password" class="form-control" placeholder="Password">
                  </div>
                  <button type="submit" class="btn btn-black">Login</button>
               </form>
            <p>Non hai un account? <a href="sign-up">Clicca qui</a></p>
            </div>
         </div>
      </div>
</body>
</html>
-->

templates/profilo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/signup.html
{% extends "base.html" %}
{% block title %}Registrazione{% endblock %}

{% block content %}

</div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <form method="POST">
               <h3 align="center">Sign Up</h3>
               <div class="form-group">
                 <label for="email">Email Address</label>
                 <input
                   type="email"
                   class="form-control"
                   id="email"
                   name="email"
                   placeholder="Enter email"
                 />
               </div>
               <div class="form-group">
                 <label for="name">Name</label>
                 <input
                   type="text"
                   class="form-control"
                   id="name"
                   name="name"
                   placeholder="Enter name"
                 />
               </div>
               <div class="form-group">
                 <label for="surname">Surname</label>
                 <input
                   type="text"
                   class="form-control"
                   id="surname"
                   name="surname"
                   placeholder="Enter surname"
                 />
               </div>
               <div class="form-group">
                 <label for="username">Username</label>
                 <input
                   type="text"
                   class="form-control"
                   id="username"
                   name="username"
                   placeholder="Enter username"
                 />
               </div>
               <div class="form-group">
                 <label for="password1">Password</label>
                 <input
                   type="password"
                   class="form-control"
                   id="password1"
                   name="password1"
                   placeholder="Enter password"
                 />
               </div>
               <div class="form-group">
                 <label for="password2">Password (Confirm)</label>
                 <input
                   type="password"
                   class="form-control"
                   id="password2"
                   name="password2"
                   placeholder="Confirm password"
                 />
               </div>
               <br />
               <button type="submit" class="btn btn-primary">Submit</button>
             </form>
         </div>
      </div>


{% endblock %}

templates/threads.html
{% extends "base.html" %}
{% block title %}Changed{% endblock %}

{% block content %} 
<h1>Pagina dei thread</h1>
<ul>
    {% for p in posts %}
    <li>post = {{p.content}}</li>
    {% endfor %}
</ul>


{% endblock %}